[package]
name = "terrain_generator_project"
version = "0.1.0"
edition = "2024"

[dependencies]

image = "0.25.6"

opensimplex_noise_rs = "0.3.0"

spatial2d = { git = "https://github.com/Liam19/Spatial2D" }
